version: "1.0.1"
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=yourpassword

  basic-backend:
    build:
      context: ./
      tags:
        - basic-backend
      dockerfile: Dockerfile

    environment:
      - DATABASE_URL=postgresql://postgres:yourpassword@postgres:5432/postgres

    ports:
      - 3000:3000

    depends_on:
      - postgres
